version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 20
  reviewers:
  - mjclawar
  - coralvanda
  ignore:
  - dependency-name: cython
    versions:
    - 0.29.22
    - 0.29.23
  - dependency-name: pandas
    versions:
    - 1.2.1
    - 1.2.2
    - 1.2.3
    - 1.2.4
  - dependency-name: numpy
    versions:
    - 1.19.5
    - 1.20.0
    - 1.20.1
    - 1.20.2
