# File : .pep8speaks.yml

message:  # Customize the comment made by the bot
    opened:  # Messages when a new PR is submitted
        header: "Hey, @{name}! It's me, Stratty! I found some coding style in your PR that I'm not a big fan of:"
        footer: "If you're not sure about this, feel free to talk to Michael about it, or review the [StratoDem notes](https://github.com/StratoDem/StratoDem/wiki/Python-Resources#python-coding-style-at-stratodem). He's even more opinionated than I am!"
    updated:  # Messages when new commits are added to the PR
        header: "Hey, @{name}! It's me again! :innocent: There's still some style choices you made that I find repulsive to my very transistors:"
        footer: "If you're not sure about this, feel free to talk to Michael about it, or review the [StratoDem notes](https://github.com/StratoDem/StratoDem/wiki/Python-Resources#python-coding-style-at-stratodem). He's even more opinionated than I am!"
    no_errors: "You're the bomb! I love your coding style. :tada:"

scanner:
    diff_only: False  # If True, errors caused by only the patch are shown

pycodestyle:
    max-line-length: 100  # Default is 79 in PEP8

only_mention_files_with_errors: True  # If False, a separate status comment for each file is made.
descending_issues_order: False # If True, PEP8 issues in message will be displayed in descending order of line numbers in the file
